server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://121.4.79.246:3306/db_mall?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Shadow99!
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 300000
      max-lifetime: 400000
      pool-name: HikariPool-1
      auto-commit: true
      validation-timeout: 1000

  servlet:
    multipart:
      file-size-threshold: 100MB
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    static-path-pattern: /static/**
