server:
  port: 8085
  servlet:
    context-path: /backstageEnd

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_mall?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xinyouMySQL99!
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 300000
      max-lifetime: 400000
      pool-name: HikariPool-1
      auto-commit: true
      validation-timeout: 1000

  #  ??redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password: xinyouRedis99!
    connect-timeout: 1800000  # ????
    lettuce:
      pool:
        max-active: 8     # ????????
        max-wait: -1    # ????????
        max-idle: 8     # ??????????
        min-idle: 0     # ??????????
  cache:
    cache-names: redis

  servlet:
    multipart:
      file-size-threshold: 100MB
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    static-path-pattern: /static/**
