# 数据文件夹以及访问数据文件夹的路径
file:
  root_dir: "/opt/xinyou/"
  host_path: "https://www.xinyouyanxue.com/miniBackend/file"
  image_path: "/opt/xinyou/images/"

# JWT 配置:
jwt:
  # 加密密钥
  secret: xinyouyanxue[caicai]
  # token 有效时常
  expire: 86400
  # header 名称
  header: token