# 数据文件夹以及访问数据文件夹的路径
file:
  root_dir: "C:/Users/aking/Desktop/xinyou/"
#  host_path: "http://localhost/file"
  host_path: "https://www.zl21.club:8081/file"
  image_path: "C:/Users/aking/Desktop/xinyou/images/"

# JWT 配置:
jwt:
  # 加密密钥
  secret: xinyouyanxue[caicai]
  # token 有效时常
  expire: 86400
  # header 名称
  header: token